name: Keep GitHub Actions Alive

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Keep Alive Commit
        uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
        with:
          COMMIT_MESSAGE: "Keep GitHub Actions alive"
